### ISSUE TITLE
update GetTxByHAsh

### ISSUE THREAD

**Issue by avive** [karma-coin/karmacoin-app#14] opened 2023-08-28 13:05 UTC
getTransactionByHash() should return a KC2Tx and not Transaction.

**Comment by HolyGrease** [comment] 2023-08-29 11:28
https://github.com/avive/karmacoin-app/pull/22

**Comment by HolyGrease** [comment] 2023-08-29 11:30
Duplicate of https://github.com/karma-coin/karmacoin-app/issues/13

**Closed as completed by HolyGrease** 2023-08-29 11:30 UTC
Labels: enhancement
